/* user */
module.exports.ping = require('./ping')
module.exports.opensource = require('./opensource')
module.exports.help = require('./help')
module.exports.userinfo = require('./userinfo')
module.exports.hangang = require('./hangang')
module.exports.corona = require('./corona')
module.exports.feedback = require('./feedback')
module.exports.invite = require('./invite')
module.exports.melon = require('./melon')
module.exports.profile = require('./profile')
module.exports.rev = require('./rev')
module.exports.say = require('./say')
module.exports.select = require('./select')
module.exports.translation = require('./translation')
module.exports.work = require('./work')
module.exports.TeamHope = require('./TeamHope')
module.exports.IU = require('./IU')
module.exports.tteog = require('./tteog')
module.exports.dongdong = require('./dongdong')
module.exports.botinfo = require('./botinfo')
module.exports.snipe = require('./snipe')



/* admin */
module.exports.kick = require('./kick')
module.exports.ban = require('./ban')
//module.exports.nickname = require('./nickname')
module.exports.join = require('./join')
//module.exports.vote = require('./vote')
module.exports.quit = require('./quit')
module.exports.channel = require('./channel')
module.exports.resetchannel = require('./resetchannel')
module.exports.purge = require('./purge')
module.exports.status = require('./status')
/* mod */

module.exports.eval = require('./eval')
module.exports.send = require('./send')
module.exports.restart = require('./restart')
module.exports.reload = require('./reload')